---
- hosts: all
  become: yes
  tasks:
  - name: install git
    ansible.builtin.apt:
      name: git
      state: present
  - name: install tree on ubunt
    ansible.builtin.apt:
      name: tree
      state: present
         



    
