---
- hosts: all
  become: yes
  tasks:
  - name: install apache2 in ubantu
    ansible.builtin.apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
  - name: install httpd in centos
    ansible.builtin.yum:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"
  - name: Start service httpd, if not started
    ansible.builtin.service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"

